name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Build
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/jsonbox_exporter \
        -ldflags "-X github.com/prometheus/common/version.Version=`cat VERSION` -X github.com/prometheus/common/version.Revision=`git rev-parse HEAD` -X github.com/prometheus/common/version.Branch=`git rev-parse --abbrev-ref HEAD` -X github.com/prometheus/common/version.BuildUser=`whoami` -X github.com/prometheus/common/version.BuildDate=`date +%Y%m%d-%H:%M:%S`"  \
        -v -a -trimpath jsonbox_exporter/cmd
